Activando entorno virtual...
Iniciando la aplicaci√≥n SCAIE...
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/Users/arturopinzon/Desktop/scAIe - Sistema Agente/plataforma_agente_scaie/venv/lib/python3.9/site-packages/certifi/cacert.pem'
INFO:     Will watch for changes in these directories: ['/Users/arturopinzon/Desktop/scAIe - Sistema Agente/plataforma_agente_scaie']
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     Started reloader process [46396] using WatchFiles
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/Users/arturopinzon/Desktop/scAIe - Sistema Agente/plataforma_agente_scaie/venv/lib/python3.9/site-packages/certifi/cacert.pem'
INFO:     Started server process [46415]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:50094 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:50098 - "GET /api/dashboard/stats HTTP/1.1" 200 OK
INFO:     127.0.0.1:50142 - "GET /api/dashboard/recent-activity HTTP/1.1" 200 OK
INFO:     127.0.0.1:50147 - "GET /api/agent/stats HTTP/1.1" 200 OK
INFO:     127.0.0.1:50149 - "GET /api/contacts/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:50197 - "GET /api/contacts/stats HTTP/1.1" 422 Unprocessable Entity
